Vagrant::Config.run do |config|
  config.vm.box       = "precise64"
  config.vm.box_url   = "http://files.vagrantup.com/precise64.box"
  #config.vm.provision :shell, :path => "install.sh"

  config.vm.provision :shell do |shell|
    shell.inline = "mkdir -p /etc/puppet/modules;
                  puppet module install puppetlabs/apt"
  end

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file = "default.pp"
    module_path = "puppet/modules"
    puppet.options = "--debug --verbose"
  end
  config.vm.host_name = "spaasvm"
  #config.vm.network :bridged
  config.vm.network :bridged, :bridge => 'en0: Wi-Fi (AirPort)'
  #config.vm.forward_port 8000, 8080
  #config.vm.network :forwarded_port, guest: 8000, host: 1234
end
