#!/bin/bash

LOCALDIR="$( cd "$( dirname "$0" )" && pwd )" 
. $LOCALDIR/lib/library.sh


delete_service() {
  local IMAGE="spi-$1"
  local CONTAINER="sp-$1"

  local current_id=$(docker ps -a|grep $CONTAINER|tr -s ' ' | cut -d ' ' -f 1)

  if [[ -n $current_id ]]; then
     local running_id=$(docker ps |grep $CONTAINER|tr -s ' ' | cut -d ' ' -f 1)
     if [[ -n $running_id ]]; then
      docker_boot=$(docker stop $current_id)
      echo "Simple Paas: $CONTAINER halted"
     fi
     docker_boot=$(docker rm $CONTAINER)
     echo "Simple Paas: $CONTAINER destroyed"
  else
    echo "Simple PaaS: $CONTAINER not running"
  fi
}


echo "Simple PaaS: Uninstalling core local components"

for SERVICE in `tac $LOCALDIR/lib/services`
do
  delete_service $SERVICE
done

delete_service control_plane

echo ""
echo "Simple PaaS: Installation Removed, Simple PaaS is not running."
