#!/bin/bash

if [ -z "$1" ]
then
  echo "useage: $0 <domain (eg: dev.muon.io)>"
  exit 1
fi

export MUON_DOMAIN=$1

LOCALDIR="$( cd "$( dirname "$0" )" && pwd )" 

. $LOCALDIR/lib/library.sh


boot_control_plane() {
  local IMAGE="sp_platform/spi_control_plane"
  local CONTAINER="sp-control_plane"
  local NUCLEUS=$(lookup_nucleus_ip)

  echo "Muon: Starting the Local Control Plane"
  local current_id=$(docker ps -a|grep $CONTAINER|tr -s ' ' | cut -d ' ' -f 1)
  if [[ -n $current_id ]]; then
     local running_id=$(docker ps |grep $CONTAINER|tr -s ' ' | cut -d ' ' -f 1)
     if [[ -z $running_id ]]; then
      docker_boot=$(docker start $current_id)
     fi
     echo "Muon: Control Plane already exists and is running with ID $current_id"
  else
    echo "Muon: Booting Control Plane, nucleus = $NUCLEUS"
    CP_PS=$(docker run -e "MUON_DOMAIN=$MUON_DOMAIN" -e MUON_NUCLEUS_PORT=7777 -e MUON_NUCLEUS_HTTP_PORT=8080 -e "MUON_NUCLEUS_HOST=$NUCLEUS" -e "CP_DOCKER_HOST=172.17.42.1" -e "CP_DOCKER_PORT=4321" --name="$CONTAINER" -d $IMAGE)
  fi
}

boot_nucleus() {
  local IMAGE="sp_platform/spi_nucleus"
  local CONTAINER="sp-nucleus"

  echo "Muon: Starting the Local Nucleus"
  local current_id=$(docker ps -a|grep $CONTAINER|tr -s ' ' | cut -d ' ' -f 1)
  if [[ -n $current_id ]]; then
     local running_id=$(docker ps |grep $CONTAINER|tr -s ' ' | cut -d ' ' -f 1)
     if [[ -z $running_id ]]; then
      docker_boot=$(docker start $current_id)
     fi
     echo "Muon: Nucleus exists and is running with ID $current_id"
  else
    echo "Muon: Booting Control Plane"
    CP_PS=$(docker run -e "MUON_DOMAIN=$MUON_DOMAIN" --name="$CONTAINER" -d $IMAGE)
  fi

  local NUCLEUS=$(lookup_nucleus_ip)
  echo "Muon: Nucleus is running on IP $NUCLEUS"

}


## TODO, possibly install a daemon instead of this socat run?

echo "Muon: Creating connection to local Docker daemon"

#TODO, this is not encrypted/ authorised, use a secured version below
#any docker container could connect to the docker API with this.
socat TCP4-LISTEN:4321,fork,reuseaddr,range=172.17.0.0/8 UNIX:/var/run/docker.sock&

## TODO, generate an SSL cert.
## TODO, generate a new container API image with that SSL cert
## TODO, use the below command to start the local port forward over SSL
#socat OPENSSL-LISTEN:4321,fork,reuseaddr,cert=cert.pem,cafile=cert.pem,key=key.pem UNIX:/var/run/docker.sock

echo "Muon: Connection to local Docker Daemon Initialised"
  boot_nucleus
  boot_control_plane
  for SERVICE in `cat $LOCALDIR/lib/services`
  do
    boot_service $SERVICE $MUON_DOMAIN
    sleep 3
  done

echo ""
echo "Muon: Dev Installation Completed, Muon Cell is running."
