#!/bin/bash

## TODO, possibly install a daemon instead?


#TODO, this is not encrypted/ authorised, use a secured version below
#any docker container could connect to the docker API with this.
socat TCP4-LISTEN:4321,fork,reuseaddr,range=172.17.0.0/8 UNIX:/var/run/docker.sock&

## TODO, generate an SSL cert.
## TODO, generate a new container API image with that SSL cert
## TODO, use the below command to start the local port forward over SSL
#socat OPENSSL-LISTEN:4321,fork,reuseaddr,cert=cert.pem,cafile=cert.pem,key=key.pem UNIX:/var/run/docker.sock

echo "Simple PaaS: Connection to local Docker Daemon Initialised"


##TODO, install or verify existence of the containerapi container

echo "Simple PaaS: Container API is installed and functional"