#!/bin/bash

delete_service() {
  local IMAGE="spi-$1"
  local CONTAINER="sp-$1"

  local current_id=$(docker ps -a|grep $CONTAINER|tr -s ' ' | cut -d ' ' -f 1)

  if [[ -n $current_id ]]; then
     local running_id=$(docker ps |grep $CONTAINER|tr -s ' ' | cut -d ' ' -f 1)
     if [[ -n $running_id ]]; then
      docker_boot=$(docker stop $current_id)
      echo "Simple Paas: $CONTAINER halted"
     fi
     docker_boot=$(docker rm $CONTAINER)
     echo "Simple Paas: $CONTAINER destroyed"
  else
    echo "Simple PaaS: $CONTAINER not running"
  fi
}


echo "Simple PaaS: Uninstalling core local components"

delete_service gene-expressor
delete_service phenotype-monitor
delete_service gene-store
delete_service control-plane

echo ""
echo "Simple PaaS: Installation Removed, Simple PaaS is not running."
