#!/bin/bash

LOCALDIR="$( cd "$( dirname "$0" )" && pwd )" 

. $LOCALDIR/../lib/library.sh

CONTROL_PLANE=$(lookup_control-plane_ip)
echo "Simple PaaS: Checking control plane status running at $CONTROL_PLANE"

CONTROL_PLANE_STATUS=$(wait_for_control_plane)

if [ "$CONTROL_PLANE_STATUS" != "FAILED" ]; then
  echo "Simple PaaS: Control Plane is running and available"
  
  echo $(curl --silent http://$CONTROL_PLANE:8080/container)
  
else
  echo "Simple PaaS: Control Plane is NOT RUNNING"
fi