FROM nodejs-image
WORKDIR /spaas
RUN git clone https://github.com/fuzzy-logic/sp_proxy.git
WORKDIR /spaas/sp_proxy
RUN /spaas/nodejs/bin/npm install
EXPOSE 8080
ENTRYPOINT /spaas/nodejs/bin/node app.js
